server:
  port: 8881
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qq1500883200/demo.git
          #username:
          #password:
          #search-paths: config-repo
          basedir: D:/workspase/demo

